{{- if .Values.keda.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "common.names.fullname" . }}-web-scaler
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    openproject/process: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.names.fullname" . }}-web
  pollingInterval: {{ .Values.keda.pollingInterval | default 30 }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod | default 300 }}
  minReplicaCount: {{ .Values.keda.minReplicaCount | default 1 }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount | default 10 }}
  {{- if .Values.keda.fallback }}
  fallback:
    {{- toYaml .Values.keda.fallback | nindent 4 }}
  {{- end }}
  {{- with .Values.keda.advanced }}
  advanced:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.keda.triggers }}
  triggers:
  {{- range .Values.keda.triggers }}
  - type: {{ .type }}
    {{- if .metadata }}
    metadata:
      {{- range $key, $value := .metadata }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
    {{- with .authenticationRef }}
    authenticationRef:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- else }}
  # No triggers defined - KEDA will not scale
  triggers: []
  {{- end }}
{{- end }}