{{- if and .Values.rustfs.bundled .Values.rustfs.consoleIngress.enabled }}
{{- $host := required "rustfs.consoleIngress.host is required when rustfs.consoleIngress.enabled is true" .Values.rustfs.consoleIngress.host }}
---
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "openproject.rustfsFullname" . }}-console
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: rustfs
  {{- if or .Values.rustfs.consoleIngress.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.rustfs.consoleIngress.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.rustfs.consoleIngress.ingressClassName }}
  ingressClassName: {{ .Values.rustfs.consoleIngress.ingressClassName }}
  {{- end }}
  {{- if and .Values.rustfs.consoleIngress.tls.enabled .Values.rustfs.consoleIngress.tls.secretName }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: "{{ .Values.rustfs.consoleIngress.tls.secretName }}"
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ .Values.rustfs.consoleIngress.path }}
            pathType: {{ .Values.rustfs.consoleIngress.pathType }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "openproject.rustfsServiceHost" $) "servicePort" "console" "context" $) | nindent 14 }}
...
{{- end }}
