{{- if and .Values.openproject.railsSecretKey.enabled (not .Values.openproject.railsSecretKey.existingSecret) }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ include "common.names.fullname" . }}-rails-secret-key"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  {{- $name := printf "%s-rails-secret-key" (include "common.names.fullname" .) }}
  {{- $existing := (lookup "v1" "Secret" .Release.Namespace $name) | default dict }}
  {{- $existingData := (get $existing "data") | default dict }}
  {{- $secret := (get $existingData "SECRET_KEY_BASE") | default (randAlphaNum 64 | b64enc) }}

  SECRET_KEY_BASE: {{ $secret | quote }}
 
...
{{- end }}
