---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ include "common.names.fullname" . }}-core"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data: # reset data to make sure only keys defined below remain
stringData:
  {{- if .Values.postgresql.bundled }}
  DATABASE_HOST: {{ printf "%s-postgresql.%s.svc.%s" .Release.Name .Release.Namespace .Values.clusterDomain | quote }}
  DATABASE_PORT: "{{ .Values.postgresql.primary.service.ports.postgresql }}"
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}@{{ include "common.names.dependency.fullname" (dict "chartName" "postgresql" "chartValues" .Values.postgresql "context" $) }}:{{ .Values.postgresql.primary.service.ports.postgresql }}/{{ .Values.postgresql.auth.database }}"
  {{- else }}
  DATABASE_HOST: "{{ .Values.postgresql.connection.host }}"
  DATABASE_PORT: "{{ .Values.postgresql.connection.port }}"
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}@{{ .Values.postgresql.connection.host }}:{{ .Values.postgresql.connection.port }}/{{ .Values.postgresql.auth.database }}"
  {{- end }}
  {{- if .Values.postgresql.options.pool }}
  OPENPROJECT_DB_POOL: {{ .Values.postgresql.options.pool | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.requireAuth }}
  OPENPROJECT_DB_REQUIRE_AUTH: {{ .Values.postgresql.options.requireAuth | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.channelBinding }}
  OPENPROJECT_DB_CHANNEL_BINDING: {{ .Values.postgresql.options.channelBinding | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.connectTimeout }}
  OPENPROJECT_DB_CONNECT_TIMEOUT: {{ .Values.postgresql.options.connectTimeout | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.clientEncoding }}
  OPENPROJECT_DB_CLIENT_ENCODING: {{ .Values.postgresql.options.clientEncoding | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.keepalives }}
  OPENPROJECT_DB_KEEPALIVES: {{ .Values.postgresql.options.keepalives | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.keepalivesIdle }}
  OPENPROJECT_DB_KEEPALIVES_IDLE: {{ .Values.postgresql.options.keepalivesIdle | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.keepalivesInterval }}
  OPENPROJECT_DB_KEEPALIVES_INTERVAL: {{ .Values.postgresql.options.keepalivesInterval | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.keepalivesCount }}
  OPENPROJECT_DB_KEEPALIVES_COUNT: {{ .Values.postgresql.options.keepalivesCount | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.replication }}
  OPENPROJECT_DB_REPLICATION: {{ .Values.postgresql.options.replication | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.gssencmode }}
  OPENPROJECT_DB_GSSENCMODE: {{ .Values.postgresql.options.gssencmode | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.sslmode }}
  OPENPROJECT_DB_SSLMODE: {{ .Values.postgresql.options.sslmode | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.sslcompression }}
  OPENPROJECT_DB_SSLCOMPRESSION: {{ .Values.postgresql.options.sslcompression | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.sslcert }}
  OPENPROJECT_DB_SSLCERT: {{ .Values.postgresql.options.sslcert | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.sslkey }}
  OPENPROJECT_DB_SSLKEY: {{ .Values.postgresql.options.sslkey | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.sslpassword }}
  OPENPROJECT_DB_SSLPASSWORD: {{ .Values.postgresql.options.sslpassword | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.sslrootcert }}
  OPENPROJECT_DB_SSLROOTCERT: {{ .Values.postgresql.options.sslrootcert | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.sslcrl }}
  OPENPROJECT_DB_SSLCRL: {{ .Values.postgresql.options.sslcrl | toString }}
  {{- end }}
  {{- if .Values.postgresql.options.sslMinProtocolVersion }}
  OPENPROJECT_DB_SSL_MIN_PROTOCOL_VERSION: {{ .Values.postgresql.options.sslMinProtocolVersion | toString }}
  {{- end }}
  {{ $secret := (lookup "v1" "Secret" .Release.Namespace (default "_" .Values.openproject.admin_user.secret)) | default (dict "data" dict) -}}
  OPENPROJECT_SEED_ADMIN_USER_PASSWORD: {{ default .Values.openproject.admin_user.password (get $secret.data .Values.openproject.admin_user.secretKeys.password | b64dec) | quote }}
  OPENPROJECT_SEED_ADMIN_USER_PASSWORD_RESET: {{ .Values.openproject.admin_user.password_reset | quote }}
  OPENPROJECT_SEED_ADMIN_USER_NAME: {{ .Values.openproject.admin_user.name | quote }}
  OPENPROJECT_SEED_ADMIN_USER_MAIL: {{ .Values.openproject.admin_user.mail | quote }}
  {{- if .Values.openproject.admin_user.locked }}
  OPENPROJECT_SEED_ADMIN_USER_LOCKED: "true"
  {{- end }}
  OPENPROJECT_HTTPS: {{ (.Values.develop | ternary "false" .Values.openproject.https) | quote }}
  OPENPROJECT_SEED_LOCALE: {{ .Values.openproject.seed_locale | quote }}
  {{- if .Values.ingress.enabled }}
  OPENPROJECT_HOST__NAME: {{ .Values.openproject.host | default .Values.ingress.host | quote }}
  {{- else if .Values.openproject.host }}
  OPENPROJECT_HOST__NAME: {{ .Values.openproject.host | quote }}
  {{- end }}
  OPENPROJECT_HSTS: {{ .Values.openproject.hsts | quote }}
  OPENPROJECT_RAILS__CACHE__STORE: {{ .Values.openproject.cache.store | quote }}
  OPENPROJECT_RAILS__RELATIVE__URL__ROOT: {{ .Values.openproject.railsRelativeUrlRoot | default "" | quote }}
  POSTGRES_STATEMENT_TIMEOUT: {{ .Values.openproject.postgresStatementTimeout | quote }}
...
