{{- if .Values.cron.environment }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ include "common.names.fullname" . }}-cron-environment"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data: # reset data to make sure only keys defined below remain
stringData:
  # Additional environment variables
  {{- range $key, $value := omit .Values.cron.environment "IMAP_USERNAME" "IMAP_PASSWORD" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{ $secret := (lookup "v1" "Secret" .Release.Namespace (default "_" .Values.cron.existingSecret)) | default (dict "data" dict) -}}
  IMAP_USERNAME: {{
    default .Values.cron.environment.IMAP_USERNAME (get $secret.data .Values.cron.secretKeys.imapUsername | b64dec) | quote
  }}
  IMAP_PASSWORD: {{
    default .Values.cron.environment.IMAP_PASSWORD (get $secret.data .Values.cron.secretKeys.imapPassword | b64dec) | quote
  }}
...
{{- end }}
