{{- if .Values.cron.environment }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ include "common.names.fullname" . }}-cron-environment"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data: # reset data to make sure only keys defined below remain
stringData:
  # Additional environment variables
  {{- range $key, $value := .Values.cron.environment }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
...
{{- end }}
