{{- if .Values.backup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-backup
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: backup
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data: # reset data to make sure only keys defined below remain
stringData:
  BACKUP_ENDPOINT: {{ required "backup.s3.endpoint is required when backup.enabled" .Values.backup.s3.endpoint | quote }}
  BACKUP_BUCKET: {{ required "backup.s3.bucket is required when backup.enabled" .Values.backup.s3.bucket | quote }}
  {{- if .Values.backup.s3.region }}
  BACKUP_REGION: {{ .Values.backup.s3.region | quote }}
  {{- end }}
  {{- if not .Values.backup.s3.auth.existingSecret }}
  BACKUP_ACCESS_KEY_ID: {{ required "backup.s3.auth.accessKeyId is required when no existingSecret is set" .Values.backup.s3.auth.accessKeyId | quote }}
  BACKUP_SECRET_ACCESS_KEY: {{ required "backup.s3.auth.secretAccessKey is required when no existingSecret is set" .Values.backup.s3.auth.secretAccessKey | quote }}
  {{- end }}
  KOPIA_CACHE_DIRECTORY: "/mnt/cache"
  DUMP_NAME: {{ include "common.names.fullname" . | quote }}
  ATTACHMENTS_STORAGE: {{ if .Values.s3.enabled }}"s3"{{ else }}"local"{{ end }}
  ATTACHMENTS_LOCAL_PATH: "/var/openproject/assets"
  {{- if .Values.backup.monitorHeartbeatUrl }}
  BACKUP_MONITOR_HEARTBEAT_URL: {{ .Values.backup.monitorHeartbeatUrl | quote }}
  {{- end }}
  {{- if .Values.backup.verification.monitorHeartbeatUrl }}
  BACKUP_VERIFICATION_MONITOR_HEARTBEAT_URL: {{ .Values.backup.verification.monitorHeartbeatUrl | quote }}
  {{- end }}
  {{- if .Values.backup.kopiaPassword }}
  KOPIA_PASSWORD: {{ .Values.backup.kopiaPassword | quote }}
  {{- end }}
  {{- if .Values.backup.replica.enabled }}
  REPLICA_ENDPOINT: {{ required "backup.replica.s3.endpoint is required when backup.replica.enabled" .Values.backup.replica.s3.endpoint | quote }}
  REPLICA_BUCKET: {{ required "backup.replica.s3.bucket is required when backup.replica.enabled" .Values.backup.replica.s3.bucket | quote }}
  {{- if .Values.backup.replica.s3.region }}
  REPLICA_REGION: {{ .Values.backup.replica.s3.region | quote }}
  {{- end }}
  {{- if not .Values.backup.replica.s3.auth.existingSecret }}
  REPLICA_ACCESS_KEY_ID: {{ required "backup.replica.s3.auth.accessKeyId is required when backup.replica.enabled and no existingSecret" .Values.backup.replica.s3.auth.accessKeyId | quote }}
  REPLICA_SECRET_ACCESS_KEY: {{ required "backup.replica.s3.auth.secretAccessKey is required when backup.replica.enabled and no existingSecret" .Values.backup.replica.s3.auth.secretAccessKey | quote }}
  {{- end }}
  {{- end }}
...
{{- end }}
