{{- if .Values.openproject.oidc.enabled }}
---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ include "common.names.fullname" . }}-oidc"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
stringData:
  # OpenID Connect settings
  {{ $oidc_prefix := printf "OPENPROJECT_OPENID__CONNECT_%s" (upper .Values.openproject.oidc.provider) }}
  {{ $oidc_prefix }}_DISPLAY__NAME: {{ .Values.openproject.oidc.provider | quote }}
  {{ $oidc_prefix }}_HOST: {{ .Values.openproject.oidc.host | quote }}
  {{ $oidc_prefix }}_IDENTIFIER: {{ .Values.openproject.oidc.identifier | quote }}
  {{ $oidc_prefix }}_SECRET: {{ .Values.openproject.oidc.secret | quote }}
  {{ $oidc_prefix }}_AUTHORIZATION__ENDPOINT: {{ .Values.openproject.oidc.authorizationEndpoint | quote }}
  {{ $oidc_prefix }}_TOKEN__ENDPOINT: {{ .Values.openproject.oidc.tokenEndpoint | quote }}
  {{ $oidc_prefix }}_USERINFO__ENDPOINT: {{ .Values.openproject.oidc.userinfoEndpoint | quote }}
  {{ $oidc_prefix }}_END__SESSION__ENDPOINT: {{ .Values.openproject.oidc.endSessionEndpoint | quote }}
  {{ $oidc_prefix }}_SCOPE: {{ .Values.openproject.oidc.scope | quote }}
  # Until https://community.openproject.org/wp/42390 is fixed (probably 12.5) we need the following setting
  OPENPROJECT_SELF__REGISTRATION: "3"
...
{{- end }}
