apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: ai-proxy-config
spec:
  plugins:
    - name: prometheus
      enable: true
    - name: key-auth
      enable: true
    - name: ai-proxy-multi
      enable: true
      config:
        balancer:
          algorithm: roundrobin
        instances:
          - name: main
            provider: {{ .Values.route.provider | quote }}
            auth:
              header:
                Authorization: "Bearer {{ .Values.route.apiKey | quote }}"
            options:
              model: {{ .Values.route.model | quote}}
            override:
              endpoint: {{ .Values.route.baseURL | quote }}