{{- if .Values.apisixInitialConfig.enabled }}
# Helps the config seeder script identify the apisix pod before it passes it's readiness check to configure it
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-apisix-admin-headless
  namespace: {{ .Release.Namespace | quote }}
spec:
  clusterIP: None #  headless
  publishNotReadyAddresses: true
  ports:
    - port: 9180
      targetPort: 9180
  selector:
    app.kubernetes.io/name: apisix
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}