apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config-seeder-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  seed.py: |
    #!/usr/bin/env python3
    import urllib.request
    import urllib.error
    import time
    import sys
    import json
    import os
    from datetime import datetime

    url = "http://{{ include "common.names.fullname" . }}-apisix-admin-headless:9180/apisix/admin/configs"
    headers = {
        "X-API-KEY": os.getenv("ADMIN_API_KEY", ""),
        "Content-Type": "application/json",
        "X-DIGEST": str(datetime.now())
    }

    # Wait for APISIX Admin API to be ready
    print("Waiting for APISIX Admin API...", flush=True)
    while True:
        try:
            req = urllib.request.Request(url, headers={"X-API-KEY": headers["X-API-KEY"]})
            with urllib.request.urlopen(req) as response:
                if response.status == 200:
                    break
        except Exception as e:
           print(f"Error: {e}", flush=True)
        time.sleep(2)

    # function that makes apisix auth schema work like the openai-compatible auth schema instead
    auth_rewrite_function = "return function(conf, ctx) local auth = ngx.req.get_headers()[\"Authorization\"] if auth then local token = auth:match(\"^[Bb]earer%s+(.+)$\") if token then ngx.req.set_header(\"Authorization\", token) end end end"
    auth_plugins = {
         "serverless-pre-function": {
             "phase": "rewrite",
             "functions": [auth_rewrite_function]
         },
         "key-auth": {
             "header": "Authorization",
             "hide_credentials": True
         },
      }

    consumer_data = json.loads(os.getenv("API_CONSUMERS", "[]"))
    apisix_consumers = [
        {
            "username": consumer["name"],
            "plugins": {
                "key-auth": {
                    "key": consumer["key"]
                },
                "ai-rate-limiting": {
                    "limit": {{ .Values.apisixConfig.consumerUsageLimits.numTokens}},
                    "time_window": {{ .Values.apisixConfig.consumerUsageLimits.timeWindowSeconds }},
                    "limit_strategy": {{ .Values.apisixConfig.consumerUsageLimits.limitStrategy | quote }},
                    "rejected_code": 429
                },
            }
        } for consumer in consumer_data
    ]

    # the serverless function makes sure the auth headers are the same as when an openai compatible endpoint
    config = {
        "routes": [
            {{- range $id, $route := .Values.apisixConfig.routes }}

            {{- $uri := "" }}

            {{- if eq $route.type "embedding" }}
              {{- $uri = "/v1/embeddings" }}
            {{- else if eq $route.type "completion" }}
              {{- $uri = "/v1/chat/completions" }}
            {{- else }}
              {{- fail (printf "Invalid route type: %s. Allowed: embedding or completion." $route.type ) }}
            {{- end }}
            {{- $baseURL := $route.baseURL }}
            {{- if eq $route.provider "selfHosted" }}
            {{- $vllmConfig := get $.Values.vllmConfigs $route.vllmConfigId }}
            {{- $baseURL = printf "http://%s:%d%s" ($route.vllmConfigId | kebabcase | lower) ($vllmConfig.service.port | default 8000 | int ) $uri }}
            {{- end }}
            {
                "id": {{ $id | quote }},
                "uri": {{ $uri | quote }},
                "priority": 10,
                "vars": [
                    ["post_arg.model", "~~", "^({{- range $index, $model := $route.models }}{{ if $index }}|{{ end }}{{ regexQuoteMeta $model.name }}{{ end }})$"]
                ],
                "plugins": {
                    **auth_plugins,
                    "prometheus": {},
                    "ai-proxy": {
                        "provider": "{{ $route.providerFormat }}",
                        "auth": {
                            "header": {
                                "Authorization": f"Bearer {os.getenv("{{ $id }}-apiKey", "")}"
                            }
                        },
                        "override": {
                            "endpoint": "{{ $baseURL }}"
                        }
                    },
                    "ai-loop-guard": {}
                },
                "upstream": {
                    "type": "roundrobin",
                    "nodes": {
                        "main": 1
                    }
                }
            },
            {{- end }}
            {
                "id": "completion-unallowed-model",
                "uri": "/v1/chat/completions",
                "priority": 1,
                "plugins": {
                    **auth_plugins,
                    "mocking": {
                        "with_mock_header": False,
                        "response_status": 404,
                        "response_example":  json.dumps(json.loads("""{"error_msg": "model not found", "description": "Please check the /v1/models endpoint to get the available models."}"""))
                    }
                }
            },
            {
                "id": "embeddings-unallowed-model",
                "uri": "/v1/embeddings",
                "priority": 1,
                "plugins": {
                    **auth_plugins,
                    "mocking": {
                        "with_mock_header": False,
                        "response_status": 404,
                        "response_example":  json.dumps(json.loads("""{"error_msg": "model not found", "description": "Please check the /v1/models endpoint to get the available models."}"""))
                    }
                }
            },
            {
                "id": "models",
                "uri": "/v1/models",
                "plugins": {
                    **auth_plugins,
                    "mocking": {
                        "with_mock_header": False,
                        "response_example":  json.dumps(json.loads("""[
                                {{- $index := 0 }}
                                {{- range $id, $route := .Values.apisixConfig.routes }}
                                    {{- range $mIndex, $model := $route.models }}
                                    {{- if $index}},{{end}}
                                    {
                                        "id": "{{ $model.name }}",
                                        "object": "model",
                                        "created": {{ now.Unix }},
                                        "owned_by": "{{ $route.provider }}",
                                        "capabilities": ["{{ $route.type }}"]
                                    }
                                    {{- $index = add $index 1 }}
                                    {{- end }}
                                {{- end }}
                            ]"""))
                    }
                }
            }
        ],
        "consumers": apisix_consumers
    }


    req = urllib.request.Request(
        url,
        data=json.dumps(config, ensure_ascii=False).encode("utf-8"),
        headers=headers,
        method="PUT"
    )

    try:
        with urllib.request.urlopen(req) as response:
            print(f"HTTP Status: {response.status}", flush=True)
            print(response.read().decode("utf-8"), flush=True)
    except urllib.error.HTTPError as e:
        print(f"HTTP Error: {e.code}", flush=True)
        print(e.read().decode("utf-8"), flush=True)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", flush=True)
        sys.exit(1)

