{{- range $consumerName, $config := .Values.apisixConsumers }}
apiVersion: apisix.apache.org/v2
kind: ApisixConsumer
metadata:
  name: {{ $consumerName | lower }}
  namespace: {{ $.Release.Namespace }}
spec:
  authOptions:
    - name: key-auth
      value:
        # The unique API Key this consumer must present to pass the gateway
        key: {{ $config.apiKey | quote }}
---
{{- end }}