{{- range $id, $config := .Values.vllmConfigs }}
{{- if and $config.persistence.enabled (not $config.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" $ }}-vllm-{{ $id | kebabcase | lower }}-cache
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: vllm-{{ $id | kebabcase | lower }}
spec:
  accessModes:
    {{- toYaml $config.persistence.accessModes | nindent 4 }}
  {{- if $config.persistence.storageClass }}
  storageClassName: {{ $config.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $config.persistence.size | quote }}
---
{{- end }}
{{- end }}