{{- range $id, $config := .Values.vllmConfigs }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $id | kebabcase | lower | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: vllm-{{ $id | kebabcase | lower }}
  annotations:
    {{ toYaml $config.service.annotations | nindent 4 }}
spec:
  type: {{ $config.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ $config.service.port | default 8000 }}
      targetPort: http
      protocol: TCP
      {{- if and (eq $config.service.type "NodePort") $config.service.nodePort }}
      nodePort: {{ $config.service.nodePort }}
      {{- end }}
  selector:
    {{- include "common.labels.matchLabels" (dict "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: vllm-{{ $id | kebabcase | lower }}
---
{{- end }}
