keda:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    # Use EITHER CPU or memory, not both (to avoid double scaling)
    - type: cpu
      metadata:
        type: Utilization
        value: "70"

appInit:
  resources:
    limits:
      memory: "1Gi"
    requests:
      memory: "1Gi"