keda:
  enabled: true
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "70"
    - type: memory  
      metadata:
        type: Utilization
        value: "80"