prometheus:
  url: http://prometheus-server.monitoring.svc.cluster.local
  port: 80

rules:
  custom:
    - seriesQuery: 'puma_request_backlog{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: '^puma_request_backlog'
        as: puma_request_backlog_avg_1min
      metricsQuery: 'avg_over_time(puma_request_backlog{<<.LabelMatchers>>}[1m])'

    - seriesQuery: 'puma_busy_threads{namespace!="",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: '^puma_busy_threads'
        as: puma_busy_threads_avg_1min
      metricsQuery: 'avg_over_time(puma_busy_threads{<<.LabelMatchers>>}[1m])'
