#!/usr/bin/env ruby
require 'json'
require 'yaml'

root = File.expand_path('..', __dir__)

Dir.glob(File.join(root, 'charts/*/CHANGELOG.md')).each do |changelog_file|
  chart_dir = File.dirname(changelog_file)
  changelog = File.read changelog_file

  release_notes = changelog.split(/^## \d+\.\d+\.\d+$/)[1]
  next unless release_notes

  release_notes_file = File.join(chart_dir, 'RELEASE-NOTES.md')
  puts "Writing to #{release_notes_file}:"
  puts release_notes

  File.open(release_notes_file, 'w') do |f|
    f.write release_notes
  end
end
