#!/usr/bin/env ruby
require 'json'
require 'yaml'

root = File.expand_path('..', __dir__)

Dir.glob(File.join(root, 'charts/*/package.json')).each do |package_file|
  chart_dir = File.dirname(package_file)
  chart_file = File.join(chart_dir, 'Chart.yaml')
  next unless File.exist?(chart_file)

  new_version = JSON.parse(File.read(package_file))['version']

  contents = YAML.load_file chart_file
  contents['version'] = new_version
  File.open(chart_file, 'w') do |f|
    f.write contents.to_yaml
  end
end
