---
apiVersion: v2
name: openproject-llm-stack
description: A Helm chart for running the LLM stack for Open Project via Kubernetes
home: https://www.openproject.org/
icon: https://charts.openproject.org/logo.svg
type: application
appVersion: 1.0.0
version: 1.0.0
maintainers:
- name: OpenProject
  url: https://github.com/opf/helm-charts
dependencies:
- name: apisix
  version: "2.14.1"
  repository: "https://apache.github.io/apisix-helm-chart"
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: "^2.2.2"
- name: kube-prometheus-stack
  version: "86.2.2"
  repository: oci://ghcr.io/prometheus-community/charts
  condition: devMonitoring.enabled
annotations:
  artifacthub.io/license: GPL-3.0-only
  artifacthub.io/links: |
    - name: Homepage
      url: https://www.openproject.org/
    - name: OpenProject Community
      url: https://community.openproject.org
    - name: support
      url: https://www.openproject.org/docs/development/report-a-bug/
  artifacthub.io/signKey: |
    fingerprint: CB1CA0488A75B7471EA1B087CF56DD6A0AE260E5
    url: https://keys.openpgp.org/vks/v1/by-fingerprint/CB1CA0488A75B7471EA1B087CF56DD6A0AE260E5
