apisixConfig:
  routes: {}
  consumerUsageLimits:
    numTokens: 50000000
    timeWindowSeconds: 86400  # 24h
    limitStrategy: total_tokens
  secrets:
    name: "llm-stack-apisix-initial-config-secret"
    consumerKey: "consumers"

apisix:
  apisix:
    deployment:
      mode: standalone
      role: traditional
      role_traditional:
        config_provider: yaml
    admin:
      credentials:
        secretName: "llm-stack-apisix-admin-secret"
      allow:
        ipList:
          - 10.42.0.0/16  # other pods
    prometheus:
      enabled: true
    customPlugins:
      enabled: true
      plugins:
        - name: ai-loop-guard
          configMap:
            name: apisix-ai-loop-guard-plugin-configmap
            mounts:
              - key: ai_loop_guard.lua
                path: /opts/custom_plugins/apisix/plugins/ai-loop-guard.lua
    plugins:
      - key-auth
      - ai-proxy
      - ai-rate-limiting
      - ai-loop-guard
      - prometheus
      - serverless-pre-function
      - mocking
  etcd:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: true
  ingress:
    enabled: true


vllmConfigs: {}

# disables entire kube-prometheus-stack
devMonitoring:
  enabled: false

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      # Tell Prometheus to discover ALL ServiceMonitors in the cluster
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana.localhost
    adminPassword: admin
