apisixInitialConfig:
  enabled: true
  route:
    provider: openai-compatible
    apiKey: "anykey"
    baseURL: "" # ignored if vllm is enabled

  consumers:
    consumerA:
      apiKey: "sk-client-v1-abcdef123456"
    # you can define multiple consumers
    # consumer_B:
    #  apiKey: "sk-client-v1-xyz987654321"

apisix:
  apisix:

    deployment:
      mode: standalone
      role: traditional
      role_traditional:
        config_provider: yaml
    admin:
      credentials:
        admin: "admin-key"
      allow:
        ipList:
          - 10.42.0.0/16 # other pods
    prometheus:
      enabled: true
  etcd:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: false


vllm:
  enabled: true
  image:
    name: "vllm/vllm-openai-cpu"
    tag: "latest-arm64"
    pullPolicy: "IfNotPresent"
  replicaCount: 1
  service:
    # Do not name this service simply "vllm" as kubernetes env variables it will clash with vllm ones.
    name: vllm-service
    type: ClusterIP
    port: 8000
    annotations: {}
  model: Qwen/Qwen2.5-0.5B-Instruct
  # setting the memory utilization lower to not use up all memory in the cpu case
  # setting the dtype to float32 as cpu often cannot deal with other types
  extraArgs:
    - "--gpu-memory-utilization"
    - "0.5"
    - "--dtype"
    - "float32"
  # Environment variables (e.g., HF_TOKEN for private models, huggingface hub configurations)
  env: []
    # - name: HF_TOKEN
    #   value: "your_huggingface_token_here"
  # Resources request/limit including GPUs
  resources:
    limits:
      cpu: "4"
      memory: "16Gi"
    requests:
      cpu: "4"
      memory: "16Gi"
  # Persistence settings to cache HuggingFace/Model files locally
  persistence:
    enabled: false
    # storageClass: ""
    # existingClaim: ""
  # Node scheduling and placement configs
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podLabels: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 240
  readinessProbe:
    enabled: true
    initialDelaySeconds: 240