apisixInitialConfig:
  enabled: true
  route:
    provider: openai-compatible
    apiKey: "scaleway-api-key"
    # retrieve the project id from the scaleway project dashboard
    baseURL: "https://api.scaleway.ai/<scaleway-project-id>/v1/chat/completions" # ignored if vllm is enabled

  consumers:
    consumerA:
      apiKey: "sk-client-v1-abcdef123456"
    # you can define multiple consumers
    # consumer_B:
    #  apiKey: "sk-client-v1-xyz987654321"

apisix:
  metrics:
    serviceMonitor:
      enabled: true
  ingress:
    enabled: true
    hosts:
      - host: llm-stack.local
        paths:
          - /v1/chat/completions

vllm:
  enabled: false


devMonitoring:
  enabled: true
