apisixInitialConfig:
  enabled: true
  route:
    provider: openai-compatible
    apiKey: "your-scaleway-api-key"
    baseURL: "https://api.scaleway.ai/<API_PATH_FROM_SCALEWAY>/v1/chat/completions" # ignored if vllm is enabled

  consumers:
    consumerA:
      apiKey: "sk-client-v1-abcdef123456"
    # you can define multiple consumers
    # consumer_B:
    #  apiKey: "sk-client-v1-xyz987654321"

apisix:
  apisix:
    deployment:
      mode: standalone
      role: traditional
      role_traditional:
        config_provider: yaml
    admin:
      credentials:
        admin: "admin-key"
      allow:
        ipList:
          - 10.42.0.0/16 # other pods
    prometheus:
      enabled: true
  etcd:
    enabled: false
  metrics:
    serviceMonitor:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - host: llm-stack.local
        paths:
          - /v1/chat/completions

vllm:
  enabled: false
