--
-- ai-loop-guard: detect bad LLM output, i.e. looped repetition, on a streaming response and cut the stream.
--
local core       = require("apisix.core")
local cjson      = require("cjson.safe")

local plugin_name = "ai-loop-guard"

local schema = {
    type = "object",
    properties = {
        -- rolling window of generated text kept for analysis, in bytes
        window_size = { type = "integer", minimum = 128, maximum = 65536,
                        default = 4096 },
        -- run detection at most once per this many newly generated bytes
        check_every = { type = "integer", minimum = 1, default = 64 },

        -- looped repeat detector: fires when the tail of the window is
        -- p-periodic for some p <= max_period, repeated >= min_repeats times
        seed_size     = { type = "integer", minimum = 4, maximum = 512,
                          default = 24 },
        min_repeats   = { type = "integer", minimum = 2, maximum = 32,
                          default = 4 },
        max_period    = { type = "integer", minimum = 1, maximum = 8192,
                          default = 512 },
        max_candidates = { type = "integer", minimum = 1, maximum = 64,
                           default = 16 },
        -- a match must also span this many bytes, so a run of identical
        -- characters ("-----", deep indentation) is not a period-1 "loop"
        min_match_bytes = { type = "integer", minimum = 1, default = 48 },
        enable_logging = { type = "boolean", default = false },
        enable_prometheus_metrics = { type = "boolean", default = true},
    },
}

local prometheus_counter_num_ai_loop_guard_triggered
local prometheus_histogram_ai_loop_guard_detected_period

local _M = {
    version  = 0.1,
    -- must be lower than ai-proxy (1040). Keep below the moderation plugins
    -- (aliyun 1029 / aws 1031 / lakera 1028) so they see unmodified chunks.
    priority = 1027,
    name     = plugin_name,
    schema   = schema,
}


function _M.check_schema(conf)
    return core.schema.check(schema, conf)
end

local function init_prometheus_metrics()
    if not prometheus_counter_num_ai_loop_guard_triggered then
        local prometheus = require("apisix.plugins.prometheus.exporter")
        local prom_dict = prometheus.get_prometheus()
        if prom_dict then
            prometheus_counter_num_ai_loop_guard_triggered = prom_dict:counter(
                "ai_loop_guard_trigger_count",
                "Total number of times the ai-loop-guard plugin was triggered",
                {"route_id", "status", "consumer"}
            )
            prometheus_histogram_ai_loop_guard_detected_period = prom_dict:histogram(
                "ai_loop_guard_detected_period",
                "Histogram of detected repetition periods",
                {"route_id", "status", "consumer"},
                {5, 10, 15, 20, 25, 30, 35, 40, 45, 50}
            )
        end
    end
end



-- s has a period x where p % x == 0  <=>  s[i] == s[i+p] for all i  <=>  s:sub(1,#s-p) == s:sub(p+1)
local function has_period(s, p)
    local n = #s
    if p <= 0 or p >= n then
        return false
    end
    -- check if the characters up till the start of the last period are equal to those starting from the second period
    return string.sub(s, 1, n - p) == string.sub(s, p + 1)
end


-- Find the period of a repeating tail, if any.
--
-- 1. take the last `seed_size` bytes of the window as a probe and look for re-occurrences from the end of the window
-- 2. check whether the region up to the first re-occurrence position repeats multiple at the end of the window
--      (for at least conf.min_repeats or conf.min_match_bytes, whichever is more prohibitive)
-- 3. if no loop was found look for the next reoccurrence (up to conf.max_candidates tries)
local function find_period(window, conf)
    local window_length = #window
    local seed_size = conf.seed_size
    if window_length < seed_size * 2 then
        return nil
    end

    local seed_start = window_length - seed_size + 1
    local region_start = seed_start - conf.max_period
    if region_start < 1 then
        region_start = 1
    end


    local reversed_window = string.reverse(string.sub(window, region_start))
    local seed_reversed = string.sub(reversed_window, 1, seed_size)

    local init, tried = 2, 0
    while tried < conf.max_candidates do
        local pos = string.find(reversed_window, seed_reversed, init, true)
        if not pos then
            break
        end
        tried = tried + 1
        local candidate_period = pos - 1

        if candidate_period >= conf.max_period then
            break
        end

        -- combine needed repeats and min match bytes to look for strong signal
        local needed_repeats = conf.min_repeats
        if candidate_period * needed_repeats < conf.min_match_bytes then
            -- increase needed repeats so that candidate_period * needed_repeats >= conf.min_match_bytes
            needed_repeats = math.ceil(conf.min_match_bytes / candidate_period)
        end
        local needed_bytes = candidate_period * needed_repeats

        if needed_bytes <= window_length then
            local tail = string.sub(window, window_length - needed_bytes + 1)
            if has_period(tail, candidate_period) then
                return candidate_period, string.sub(tail, 1, candidate_period), needed_repeats
            end
        end

        init = pos + 1
    end

    return nil
end

local function get_state(ctx, conf)
    local st = ctx.ai_loop_guard
    if not st then
        st = {
            window          = "",
            stream_buffer   = "",
            latest_chunk    = nil,
            total           = 0,
            since           = 0,
            verdict         = nil,
            terminated      = false,
        }
        ctx.ai_loop_guard = st
    end
    return st
end

-- extract the text from the new chunks or append a partial chunk to an temporary buffer
local function extract_chunk_text(chunk, state)
    local new_text = ""
    local done

    if chunk and chunk ~= "" then
        -- Append the incoming network piece to our processing buffer
        -- in special networking situations chunks might arrive partially
        state.stream_buffer = state.stream_buffer .. chunk

        -- SSE chunks are split by double newlines (\n\n)
        -- safe because new lines in the json payload are escaped (\\n)
        while true do
            local start_pos, end_pos = string.find(state.stream_buffer, "\n\n", 1, true)
            if not start_pos then
                break -- Incomplete SSE event frame, wait for next body_filter execution
            end

            -- Extract a single full SSE message block
            local event_block = string.sub(state.stream_buffer, 1, start_pos - 1)
            -- Trim the consumed block out of our context buffer
            state.stream_buffer = string.sub(state.stream_buffer, end_pos + 1)

            -- Look for the standard "data: " prefix used by OpenAI/Anthropic/DeepSeek
            if string.sub(event_block, 1, 6) == "data: " then
                local json_str = string.sub(event_block, 7)

                if json_str == "[DONE]" then
                    done = true
                else
                    local res, err = cjson.decode(json_str)
                    if res then
                        state.latest_chunk = res
                        if res.choices and res.choices[1] and res.choices[1].delta then
                            local delta = res.choices[1].delta

                            -- Extract the text content chunk
                            if delta.content then
                                new_text = new_text .. delta.content
                            end
                            if delta.reasoning then
                                new_text = new_text .. delta.reasoning
                            end
                        end
                    else
                        core.log.error("Failed to parse SSE JSON: ", err)
                    end
                end
            end
        end
    end
    return new_text, done
end


-- Build the bytes that replace the current chunk when cutting the stream
local function build_terminator(state)
    local terminator = ""
    state.latest_chunk.choices = {
        {
            index = 0,
            delta = {},
            logprobs = nil,
            finish_reason = plugin_name,
            stop_reason = "loop_detected",
            token_ids = nil
        }
    }
    terminator = terminator .. "data: " .. cjson.encode(state.latest_chunk) .. "\n\n"
    terminator = terminator .. "data: [DONE]\n\n"
    return terminator
end


local function run_detectors(conf, st)

    local period, unit, reps = find_period(st.window, conf)
    if period then
        return {
            unit = unit,
            period = period,
            repeats = repeats,
        }
    end

    return nil
end


function _M.body_filter(conf, ctx)
    if ngx.status >= 400 then
        return
    end

    if conf.enable_prometheus_metrics then
        init_prometheus_metrics()
    end

    local state = get_state(ctx, conf)
    if state.terminated then
        ngx.arg[1] = nil
        ngx.arg[2] = true
        return
    end

    local new_text, done = extract_chunk_text(ngx.arg[1], state)

    if new_text and #new_text > 0 then
        state.total = state.total + #new_text
        state.since = state.since + #new_text

        local window = state.window .. new_text
        if #window > conf.window_size then
            window = string.sub(window, -conf.window_size)
        end
        state.window = window

        if (state.since >= conf.check_every) or done then
            state.since = 0
            state.verdict = run_detectors(conf, state)
        end
    end

    if not state.verdict then
        return
    end

    if conf.enable_logging then
        core.log.warn(plugin_name, ": ",
                     "loop detected after ", state.total, " generated bytes: ",
                     "period=", state.verdict.period,
                     ", repeats=", state.verdict.repeats,
                     ", model=", ctx.var.llm_model or "",
                     ", route_id=", ctx.var.route_id or "")
    end

    -- sending the termination message to the client and closing the stream from the server
    state.terminated = true
    ngx.arg[1] = build_terminator(state)
    ngx.arg[2] = true

    -- logging prometheus metrics
    if conf.enable_prometheus_metrics then
        local route_id = ctx.route_id or "unknown"
        local status = tostring(ngx.status)
        local consumer = ctx.consumer_name or "anonymous"
        prometheus_counter_num_ai_loop_guard_triggered:inc(1, {route_id, status, consumer})
        prometheus_histogram_ai_loop_guard_detected_period:observe(state.verdict.period, {route_id, status, consumer})
    end
end

return _M
