name: Lint and Test Charts

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          if grep -qx 'charts/openproject' <<< "$changed"; then
            echo "openproject-changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint) WITHOUT version check
        if: github.event.pull_request.title != 'Release Tracking'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --check-version-increment=false

      - name: Run chart-testing (lint) WITH version check
        if: github.event.pull_request.title == 'Release Tracking'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --check-version-increment=true

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        if: steps.list-changed.outputs.openproject-changed == 'true'

      - name: Create restricted namespace for OpenProject
        if: steps.list-changed.outputs.openproject-changed == 'true'
        run: |
          kubectl apply -f - <<'YAML'
          apiVersion: v1
          kind: Namespace
          metadata:
            name: openproject-ct
            labels:
              pod-security.kubernetes.io/enforce: restricted
              pod-security.kubernetes.io/enforce-version: latest
              pod-security.kubernetes.io/audit: restricted
              pod-security.kubernetes.io/audit-version: latest
              pod-security.kubernetes.io/warn: restricted
              pod-security.kubernetes.io/warn-version: latest
          YAML

      - name: Run chart-testing (install) for OpenProject
        if: steps.list-changed.outputs.openproject-changed == 'true'
        run: |
          ct install \
            --charts charts/openproject \
            --namespace openproject-ct \
            --chart-repos bitnami=https://charts.bitnami.com/bitnami \
            --helm-extra-set-args "\
              --set environment.OPENPROJECT_HTTPS=false \
              --set persistence.accessModes=[ReadWriteOnce] \
            " \
            --helm-extra-args "--timeout 600s"
